// Code generated by protoc-gen-go. DO NOT EDIT.
// source: v1/identifiable.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Identifiable struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Identifiable) Reset()         { *m = Identifiable{} }
func (m *Identifiable) String() string { return proto.CompactTextString(m) }
func (*Identifiable) ProtoMessage()    {}
func (*Identifiable) Descriptor() ([]byte, []int) {
	return fileDescriptor_59b066868c30fc88, []int{0}
}

func (m *Identifiable) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Identifiable.Unmarshal(m, b)
}
func (m *Identifiable) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Identifiable.Marshal(b, m, deterministic)
}
func (m *Identifiable) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Identifiable.Merge(m, src)
}
func (m *Identifiable) XXX_Size() int {
	return xxx_messageInfo_Identifiable.Size(m)
}
func (m *Identifiable) XXX_DiscardUnknown() {
	xxx_messageInfo_Identifiable.DiscardUnknown(m)
}

var xxx_messageInfo_Identifiable proto.InternalMessageInfo

func (m *Identifiable) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type FindCriteria struct {
	Id                   *wrappers.StringValue `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 *wrappers.StringValue `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          *wrappers.StringValue `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *FindCriteria) Reset()         { *m = FindCriteria{} }
func (m *FindCriteria) String() string { return proto.CompactTextString(m) }
func (*FindCriteria) ProtoMessage()    {}
func (*FindCriteria) Descriptor() ([]byte, []int) {
	return fileDescriptor_59b066868c30fc88, []int{1}
}

func (m *FindCriteria) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindCriteria.Unmarshal(m, b)
}
func (m *FindCriteria) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindCriteria.Marshal(b, m, deterministic)
}
func (m *FindCriteria) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindCriteria.Merge(m, src)
}
func (m *FindCriteria) XXX_Size() int {
	return xxx_messageInfo_FindCriteria.Size(m)
}
func (m *FindCriteria) XXX_DiscardUnknown() {
	xxx_messageInfo_FindCriteria.DiscardUnknown(m)
}

var xxx_messageInfo_FindCriteria proto.InternalMessageInfo

func (m *FindCriteria) GetId() *wrappers.StringValue {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *FindCriteria) GetName() *wrappers.StringValue {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *FindCriteria) GetDescription() *wrappers.StringValue {
	if m != nil {
		return m.Description
	}
	return nil
}

func init() {
	proto.RegisterType((*Identifiable)(nil), "v1.Identifiable")
	proto.RegisterType((*FindCriteria)(nil), "v1.FindCriteria")
}

func init() { proto.RegisterFile("v1/identifiable.proto", fileDescriptor_59b066868c30fc88) }

var fileDescriptor_59b066868c30fc88 = []byte{
	// 221 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0x41, 0x4b, 0xc4, 0x30,
	0x10, 0x46, 0x69, 0x15, 0xc1, 0xec, 0xe2, 0x21, 0x20, 0x14, 0x91, 0x45, 0xf6, 0xe4, 0xc1, 0x4d,
	0xac, 0xde, 0x3d, 0x28, 0x08, 0x5e, 0x15, 0x3c, 0x78, 0x9b, 0x34, 0xb3, 0x71, 0xd8, 0x34, 0x09,
	0xe9, 0xb4, 0xfe, 0x2b, 0x7f, 0xa3, 0xd8, 0xea, 0xb2, 0xc7, 0xde, 0x3e, 0x86, 0xf7, 0xde, 0x61,
	0xc4, 0xf9, 0x50, 0x6b, 0xb2, 0x18, 0x98, 0xb6, 0x04, 0xc6, 0xa3, 0x4a, 0x39, 0x72, 0x94, 0xe5,
	0x50, 0x5f, 0xac, 0x5c, 0x8c, 0xce, 0xa3, 0x1e, 0x2f, 0xa6, 0xdf, 0xea, 0xaf, 0x0c, 0x29, 0x61,
	0xee, 0x26, 0x66, 0xbd, 0x12, 0xcb, 0x97, 0x03, 0x53, 0x9e, 0x89, 0x92, 0x6c, 0x55, 0x5c, 0x15,
	0xd7, 0xa7, 0xaf, 0x25, 0xd9, 0xf5, 0x77, 0x21, 0x96, 0xcf, 0x14, 0xec, 0x53, 0x26, 0xc6, 0x4c,
	0x20, 0x6f, 0xf6, 0xc0, 0xe2, 0xee, 0x52, 0x4d, 0x75, 0xf5, 0x5f, 0x57, 0x6f, 0x9c, 0x29, 0xb8,
	0x77, 0xf0, 0x3d, 0xfe, 0xea, 0xf2, 0x56, 0x1c, 0x07, 0x68, 0xb1, 0x2a, 0x67, 0xf0, 0x23, 0x29,
	0x1f, 0xc4, 0xc2, 0x62, 0xd7, 0x64, 0x4a, 0x4c, 0x31, 0x54, 0x47, 0x33, 0xc4, 0x43, 0xe1, 0x51,
	0x7f, 0x6c, 0x1c, 0xf1, 0x67, 0x6f, 0x54, 0x13, 0x5b, 0xdd, 0x22, 0x83, 0xdf, 0x74, 0x0c, 0xcd,
	0xee, 0x6f, 0x43, 0x22, 0x9d, 0x76, 0x6e, 0x7a, 0x88, 0x1e, 0x6a, 0x73, 0x32, 0xae, 0xfb, 0x9f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x69, 0xe5, 0x99, 0xc8, 0x45, 0x01, 0x00, 0x00,
}
