// Code generated by protoc-gen-go. DO NOT EDIT.
// source: v1/image.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// An image can be attached to a machine
type Image struct {
	Common               *Common                 `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	URL                  *wrappers.StringValue   `protobuf:"bytes,2,opt,name=URL,proto3" json:"URL,omitempty"`
	Features             []*wrappers.StringValue `protobuf:"bytes,3,rep,name=features,proto3" json:"features,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *Image) Reset()         { *m = Image{} }
func (m *Image) String() string { return proto.CompactTextString(m) }
func (*Image) ProtoMessage()    {}
func (*Image) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2b462dcc8ce95f9, []int{0}
}

func (m *Image) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Image.Unmarshal(m, b)
}
func (m *Image) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Image.Marshal(b, m, deterministic)
}
func (m *Image) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Image.Merge(m, src)
}
func (m *Image) XXX_Size() int {
	return xxx_messageInfo_Image.Size(m)
}
func (m *Image) XXX_DiscardUnknown() {
	xxx_messageInfo_Image.DiscardUnknown(m)
}

var xxx_messageInfo_Image proto.InternalMessageInfo

func (m *Image) GetCommon() *Common {
	if m != nil {
		return m.Common
	}
	return nil
}

func (m *Image) GetURL() *wrappers.StringValue {
	if m != nil {
		return m.URL
	}
	return nil
}

func (m *Image) GetFeatures() []*wrappers.StringValue {
	if m != nil {
		return m.Features
	}
	return nil
}

type ImageCreateRequest struct {
	Image                *Image   `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImageCreateRequest) Reset()         { *m = ImageCreateRequest{} }
func (m *ImageCreateRequest) String() string { return proto.CompactTextString(m) }
func (*ImageCreateRequest) ProtoMessage()    {}
func (*ImageCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2b462dcc8ce95f9, []int{1}
}

func (m *ImageCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImageCreateRequest.Unmarshal(m, b)
}
func (m *ImageCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImageCreateRequest.Marshal(b, m, deterministic)
}
func (m *ImageCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImageCreateRequest.Merge(m, src)
}
func (m *ImageCreateRequest) XXX_Size() int {
	return xxx_messageInfo_ImageCreateRequest.Size(m)
}
func (m *ImageCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ImageCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ImageCreateRequest proto.InternalMessageInfo

func (m *ImageCreateRequest) GetImage() *Image {
	if m != nil {
		return m.Image
	}
	return nil
}

type ImageUpdateRequest struct {
	Image                *Image   `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImageUpdateRequest) Reset()         { *m = ImageUpdateRequest{} }
func (m *ImageUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*ImageUpdateRequest) ProtoMessage()    {}
func (*ImageUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2b462dcc8ce95f9, []int{2}
}

func (m *ImageUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImageUpdateRequest.Unmarshal(m, b)
}
func (m *ImageUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImageUpdateRequest.Marshal(b, m, deterministic)
}
func (m *ImageUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImageUpdateRequest.Merge(m, src)
}
func (m *ImageUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_ImageUpdateRequest.Size(m)
}
func (m *ImageUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ImageUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ImageUpdateRequest proto.InternalMessageInfo

func (m *ImageUpdateRequest) GetImage() *Image {
	if m != nil {
		return m.Image
	}
	return nil
}

type ImageDeleteRequest struct {
	Identifiable         *Identifiable `protobuf:"bytes,1,opt,name=identifiable,proto3" json:"identifiable,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ImageDeleteRequest) Reset()         { *m = ImageDeleteRequest{} }
func (m *ImageDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*ImageDeleteRequest) ProtoMessage()    {}
func (*ImageDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2b462dcc8ce95f9, []int{3}
}

func (m *ImageDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImageDeleteRequest.Unmarshal(m, b)
}
func (m *ImageDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImageDeleteRequest.Marshal(b, m, deterministic)
}
func (m *ImageDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImageDeleteRequest.Merge(m, src)
}
func (m *ImageDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_ImageDeleteRequest.Size(m)
}
func (m *ImageDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ImageDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ImageDeleteRequest proto.InternalMessageInfo

func (m *ImageDeleteRequest) GetIdentifiable() *Identifiable {
	if m != nil {
		return m.Identifiable
	}
	return nil
}

type ImageGetRequest struct {
	Identifiable         *Identifiable `protobuf:"bytes,1,opt,name=identifiable,proto3" json:"identifiable,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ImageGetRequest) Reset()         { *m = ImageGetRequest{} }
func (m *ImageGetRequest) String() string { return proto.CompactTextString(m) }
func (*ImageGetRequest) ProtoMessage()    {}
func (*ImageGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2b462dcc8ce95f9, []int{4}
}

func (m *ImageGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImageGetRequest.Unmarshal(m, b)
}
func (m *ImageGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImageGetRequest.Marshal(b, m, deterministic)
}
func (m *ImageGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImageGetRequest.Merge(m, src)
}
func (m *ImageGetRequest) XXX_Size() int {
	return xxx_messageInfo_ImageGetRequest.Size(m)
}
func (m *ImageGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ImageGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ImageGetRequest proto.InternalMessageInfo

func (m *ImageGetRequest) GetIdentifiable() *Identifiable {
	if m != nil {
		return m.Identifiable
	}
	return nil
}

type ImageFindRequest struct {
	FindCriteria         *FindCriteria `protobuf:"bytes,1,opt,name=findCriteria,proto3" json:"findCriteria,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ImageFindRequest) Reset()         { *m = ImageFindRequest{} }
func (m *ImageFindRequest) String() string { return proto.CompactTextString(m) }
func (*ImageFindRequest) ProtoMessage()    {}
func (*ImageFindRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2b462dcc8ce95f9, []int{5}
}

func (m *ImageFindRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImageFindRequest.Unmarshal(m, b)
}
func (m *ImageFindRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImageFindRequest.Marshal(b, m, deterministic)
}
func (m *ImageFindRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImageFindRequest.Merge(m, src)
}
func (m *ImageFindRequest) XXX_Size() int {
	return xxx_messageInfo_ImageFindRequest.Size(m)
}
func (m *ImageFindRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ImageFindRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ImageFindRequest proto.InternalMessageInfo

func (m *ImageFindRequest) GetFindCriteria() *FindCriteria {
	if m != nil {
		return m.FindCriteria
	}
	return nil
}

type ImageListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImageListRequest) Reset()         { *m = ImageListRequest{} }
func (m *ImageListRequest) String() string { return proto.CompactTextString(m) }
func (*ImageListRequest) ProtoMessage()    {}
func (*ImageListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2b462dcc8ce95f9, []int{6}
}

func (m *ImageListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImageListRequest.Unmarshal(m, b)
}
func (m *ImageListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImageListRequest.Marshal(b, m, deterministic)
}
func (m *ImageListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImageListRequest.Merge(m, src)
}
func (m *ImageListRequest) XXX_Size() int {
	return xxx_messageInfo_ImageListRequest.Size(m)
}
func (m *ImageListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ImageListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ImageListRequest proto.InternalMessageInfo

type ImageResponse struct {
	Image                *Image   `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImageResponse) Reset()         { *m = ImageResponse{} }
func (m *ImageResponse) String() string { return proto.CompactTextString(m) }
func (*ImageResponse) ProtoMessage()    {}
func (*ImageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2b462dcc8ce95f9, []int{7}
}

func (m *ImageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImageResponse.Unmarshal(m, b)
}
func (m *ImageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImageResponse.Marshal(b, m, deterministic)
}
func (m *ImageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImageResponse.Merge(m, src)
}
func (m *ImageResponse) XXX_Size() int {
	return xxx_messageInfo_ImageResponse.Size(m)
}
func (m *ImageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ImageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ImageResponse proto.InternalMessageInfo

func (m *ImageResponse) GetImage() *Image {
	if m != nil {
		return m.Image
	}
	return nil
}

type ImageListResponse struct {
	Images               []*Image `protobuf:"bytes,1,rep,name=images,proto3" json:"images,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImageListResponse) Reset()         { *m = ImageListResponse{} }
func (m *ImageListResponse) String() string { return proto.CompactTextString(m) }
func (*ImageListResponse) ProtoMessage()    {}
func (*ImageListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2b462dcc8ce95f9, []int{8}
}

func (m *ImageListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImageListResponse.Unmarshal(m, b)
}
func (m *ImageListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImageListResponse.Marshal(b, m, deterministic)
}
func (m *ImageListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImageListResponse.Merge(m, src)
}
func (m *ImageListResponse) XXX_Size() int {
	return xxx_messageInfo_ImageListResponse.Size(m)
}
func (m *ImageListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ImageListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ImageListResponse proto.InternalMessageInfo

func (m *ImageListResponse) GetImages() []*Image {
	if m != nil {
		return m.Images
	}
	return nil
}

func init() {
	proto.RegisterType((*Image)(nil), "v1.Image")
	proto.RegisterType((*ImageCreateRequest)(nil), "v1.ImageCreateRequest")
	proto.RegisterType((*ImageUpdateRequest)(nil), "v1.ImageUpdateRequest")
	proto.RegisterType((*ImageDeleteRequest)(nil), "v1.ImageDeleteRequest")
	proto.RegisterType((*ImageGetRequest)(nil), "v1.ImageGetRequest")
	proto.RegisterType((*ImageFindRequest)(nil), "v1.ImageFindRequest")
	proto.RegisterType((*ImageListRequest)(nil), "v1.ImageListRequest")
	proto.RegisterType((*ImageResponse)(nil), "v1.ImageResponse")
	proto.RegisterType((*ImageListResponse)(nil), "v1.ImageListResponse")
}

func init() { proto.RegisterFile("v1/image.proto", fileDescriptor_b2b462dcc8ce95f9) }

var fileDescriptor_b2b462dcc8ce95f9 = []byte{
	// 450 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x93, 0x51, 0x6f, 0xd3, 0x30,
	0x14, 0x85, 0xd5, 0x76, 0x8b, 0xe0, 0x32, 0xd8, 0x66, 0x18, 0xaa, 0x22, 0x04, 0x23, 0x4f, 0xbc,
	0x34, 0x26, 0x2b, 0x20, 0x9e, 0x29, 0x5a, 0x01, 0xed, 0x29, 0xd3, 0x78, 0xe0, 0xcd, 0x6d, 0x6f,
	0x82, 0xb5, 0x24, 0x0e, 0xb6, 0x13, 0x7e, 0x09, 0x7f, 0x89, 0xdf, 0x85, 0x62, 0xbb, 0xa9, 0x23,
	0x6d, 0x9a, 0xd0, 0xde, 0x92, 0x73, 0xcf, 0x77, 0x72, 0x75, 0x8f, 0x02, 0x4f, 0xda, 0x84, 0xf2,
	0x92, 0xe5, 0x18, 0xd7, 0x52, 0x68, 0x41, 0xc6, 0x6d, 0x12, 0x1e, 0xb6, 0x09, 0x5d, 0x8b, 0xb2,
	0x14, 0x95, 0x15, 0xc3, 0x93, 0xce, 0xb4, 0xc1, 0x4a, 0xf3, 0x8c, 0xb3, 0x55, 0xe1, 0xbc, 0xe1,
	0xcb, 0x5c, 0x88, 0xbc, 0x40, 0x6a, 0xde, 0x56, 0x4d, 0x46, 0x7f, 0x4b, 0x56, 0xd7, 0x28, 0x95,
	0x9d, 0x47, 0x7f, 0x46, 0xb0, 0xff, 0xb5, 0xcb, 0x26, 0x11, 0x04, 0x36, 0x70, 0x3a, 0x3a, 0x1d,
	0xbd, 0x79, 0x74, 0x06, 0x71, 0x9b, 0xc4, 0x0b, 0xa3, 0xa4, 0x6e, 0x42, 0x62, 0x98, 0x5c, 0xa5,
	0x17, 0xd3, 0xb1, 0x31, 0xbc, 0x88, 0x6d, 0x76, 0xbc, 0xcd, 0x8e, 0x2f, 0xb5, 0xe4, 0x55, 0xfe,
	0x9d, 0x15, 0x0d, 0xa6, 0x9d, 0x91, 0x7c, 0x84, 0x07, 0x19, 0x32, 0xdd, 0x48, 0x54, 0xd3, 0xc9,
	0xe9, 0xe4, 0x4e, 0xa8, 0x77, 0x47, 0xef, 0x81, 0x98, 0xb5, 0x16, 0x12, 0x99, 0xc6, 0x14, 0x7f,
	0x35, 0xa8, 0x34, 0x79, 0x05, 0xfb, 0xe6, 0x10, 0x6e, 0xc5, 0x87, 0xdd, 0x8a, 0xc6, 0x96, 0x5a,
	0xbd, 0xc7, 0xae, 0xea, 0xcd, 0xff, 0x60, 0xdf, 0x1c, 0xf6, 0x19, 0x0b, 0xdc, 0x61, 0xef, 0xe0,
	0xc0, 0xbf, 0xa8, 0xa3, 0x8f, 0x0c, 0xed, 0xe9, 0xe9, 0xc0, 0x15, 0x2d, 0xe1, 0xd0, 0x64, 0x2d,
	0x51, 0xdf, 0x2f, 0xe8, 0x0b, 0x1c, 0x99, 0xa0, 0x73, 0x5e, 0x6d, 0xbc, 0xa4, 0x8c, 0x57, 0x9b,
	0x85, 0xe4, 0x1a, 0x25, 0x67, 0x7e, 0xd2, 0xb9, 0xa7, 0xa7, 0x03, 0x57, 0x44, 0x5c, 0xd2, 0x05,
	0x57, 0xdb, 0x9d, 0xa2, 0xb7, 0xf0, 0xd8, 0x9e, 0x00, 0x55, 0x2d, 0x2a, 0x85, 0x77, 0x1f, 0xe9,
	0x03, 0x1c, 0x7b, 0x29, 0x8e, 0x7a, 0x0d, 0x81, 0x99, 0xaa, 0xe9, 0xc8, 0xf4, 0xeb, 0x61, 0x6e,
	0x70, 0xf6, 0x77, 0x0c, 0x07, 0x46, 0xb9, 0x44, 0xd9, 0xf2, 0x35, 0x92, 0x39, 0x04, 0xb6, 0x56,
	0xf2, 0xbc, 0x77, 0x0f, 0x7a, 0x0e, 0x8f, 0x77, 0x29, 0xdb, 0x0f, 0xcd, 0x21, 0xb0, 0xa5, 0x7a,
	0xd0, 0xa0, 0xe5, 0x5b, 0x20, 0x5b, 0xa9, 0x07, 0x0d, 0x3a, 0xbe, 0x09, 0x9a, 0xc1, 0x64, 0x89,
	0x9a, 0x3c, 0xed, 0x27, 0xbb, 0x26, 0x6f, 0xfe, 0xc6, 0x5e, 0x77, 0x7a, 0xf2, 0xac, 0x1f, 0x79,
	0x85, 0x85, 0x27, 0xbd, 0x3a, 0x38, 0xdb, 0x1c, 0xf6, 0xba, 0x77, 0x0f, 0xf2, 0xba, 0xb9, 0x05,
	0xfa, 0x44, 0x7f, 0xcc, 0x72, 0xae, 0x7f, 0x36, 0xab, 0x78, 0x2d, 0x4a, 0x5a, 0xa2, 0x66, 0xc5,
	0x4c, 0x69, 0xb6, 0xbe, 0x76, 0xcf, 0xac, 0xe6, 0xb4, 0xbe, 0xce, 0xed, 0xbf, 0x4e, 0xdb, 0x64,
	0x15, 0x98, 0xa7, 0xf9, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1e, 0x17, 0x2a, 0x35, 0x41, 0x04,
	0x00, 0x00,
}
