// Code generated by protoc-gen-go. DO NOT EDIT.
// source: v1/size.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SizeConstraint_Type int32

const (
	SizeConstraint_CORES   SizeConstraint_Type = 0
	SizeConstraint_MEMORY  SizeConstraint_Type = 1
	SizeConstraint_STORAGE SizeConstraint_Type = 2
)

var SizeConstraint_Type_name = map[int32]string{
	0: "CORES",
	1: "MEMORY",
	2: "STORAGE",
}

var SizeConstraint_Type_value = map[string]int32{
	"CORES":   0,
	"MEMORY":  1,
	"STORAGE": 2,
}

func (x SizeConstraint_Type) String() string {
	return proto.EnumName(SizeConstraint_Type_name, int32(x))
}

func (SizeConstraint_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8347758cbb88e74f, []int{0, 0}
}

// a machine matches to a size in order to make them easier to categorize
type SizeConstraint struct {
	Type                 SizeConstraint_Type `protobuf:"varint,1,opt,name=type,proto3,enum=v1.SizeConstraint_Type" json:"type,omitempty"`
	Min                  uint64              `protobuf:"varint,2,opt,name=min,proto3" json:"min,omitempty"`
	Max                  uint64              `protobuf:"varint,3,opt,name=max,proto3" json:"max,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *SizeConstraint) Reset()         { *m = SizeConstraint{} }
func (m *SizeConstraint) String() string { return proto.CompactTextString(m) }
func (*SizeConstraint) ProtoMessage()    {}
func (*SizeConstraint) Descriptor() ([]byte, []int) {
	return fileDescriptor_8347758cbb88e74f, []int{0}
}

func (m *SizeConstraint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SizeConstraint.Unmarshal(m, b)
}
func (m *SizeConstraint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SizeConstraint.Marshal(b, m, deterministic)
}
func (m *SizeConstraint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SizeConstraint.Merge(m, src)
}
func (m *SizeConstraint) XXX_Size() int {
	return xxx_messageInfo_SizeConstraint.Size(m)
}
func (m *SizeConstraint) XXX_DiscardUnknown() {
	xxx_messageInfo_SizeConstraint.DiscardUnknown(m)
}

var xxx_messageInfo_SizeConstraint proto.InternalMessageInfo

func (m *SizeConstraint) GetType() SizeConstraint_Type {
	if m != nil {
		return m.Type
	}
	return SizeConstraint_CORES
}

func (m *SizeConstraint) GetMin() uint64 {
	if m != nil {
		return m.Min
	}
	return 0
}

func (m *SizeConstraint) GetMax() uint64 {
	if m != nil {
		return m.Max
	}
	return 0
}

type Size struct {
	Common               *Common           `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	Constraints          []*SizeConstraint `protobuf:"bytes,2,rep,name=constraints,proto3" json:"constraints,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Size) Reset()         { *m = Size{} }
func (m *Size) String() string { return proto.CompactTextString(m) }
func (*Size) ProtoMessage()    {}
func (*Size) Descriptor() ([]byte, []int) {
	return fileDescriptor_8347758cbb88e74f, []int{1}
}

func (m *Size) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Size.Unmarshal(m, b)
}
func (m *Size) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Size.Marshal(b, m, deterministic)
}
func (m *Size) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Size.Merge(m, src)
}
func (m *Size) XXX_Size() int {
	return xxx_messageInfo_Size.Size(m)
}
func (m *Size) XXX_DiscardUnknown() {
	xxx_messageInfo_Size.DiscardUnknown(m)
}

var xxx_messageInfo_Size proto.InternalMessageInfo

func (m *Size) GetCommon() *Common {
	if m != nil {
		return m.Common
	}
	return nil
}

func (m *Size) GetConstraints() []*SizeConstraint {
	if m != nil {
		return m.Constraints
	}
	return nil
}

type SizeCreateRequest struct {
	Size                 *Size    `protobuf:"bytes,1,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SizeCreateRequest) Reset()         { *m = SizeCreateRequest{} }
func (m *SizeCreateRequest) String() string { return proto.CompactTextString(m) }
func (*SizeCreateRequest) ProtoMessage()    {}
func (*SizeCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8347758cbb88e74f, []int{2}
}

func (m *SizeCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SizeCreateRequest.Unmarshal(m, b)
}
func (m *SizeCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SizeCreateRequest.Marshal(b, m, deterministic)
}
func (m *SizeCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SizeCreateRequest.Merge(m, src)
}
func (m *SizeCreateRequest) XXX_Size() int {
	return xxx_messageInfo_SizeCreateRequest.Size(m)
}
func (m *SizeCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SizeCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SizeCreateRequest proto.InternalMessageInfo

func (m *SizeCreateRequest) GetSize() *Size {
	if m != nil {
		return m.Size
	}
	return nil
}

type SizeUpdateRequest struct {
	Size                 *Size    `protobuf:"bytes,1,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SizeUpdateRequest) Reset()         { *m = SizeUpdateRequest{} }
func (m *SizeUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*SizeUpdateRequest) ProtoMessage()    {}
func (*SizeUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8347758cbb88e74f, []int{3}
}

func (m *SizeUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SizeUpdateRequest.Unmarshal(m, b)
}
func (m *SizeUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SizeUpdateRequest.Marshal(b, m, deterministic)
}
func (m *SizeUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SizeUpdateRequest.Merge(m, src)
}
func (m *SizeUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_SizeUpdateRequest.Size(m)
}
func (m *SizeUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SizeUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SizeUpdateRequest proto.InternalMessageInfo

func (m *SizeUpdateRequest) GetSize() *Size {
	if m != nil {
		return m.Size
	}
	return nil
}

type SizeDeleteRequest struct {
	Identifiable         *Identifiable `protobuf:"bytes,1,opt,name=identifiable,proto3" json:"identifiable,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SizeDeleteRequest) Reset()         { *m = SizeDeleteRequest{} }
func (m *SizeDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*SizeDeleteRequest) ProtoMessage()    {}
func (*SizeDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8347758cbb88e74f, []int{4}
}

func (m *SizeDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SizeDeleteRequest.Unmarshal(m, b)
}
func (m *SizeDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SizeDeleteRequest.Marshal(b, m, deterministic)
}
func (m *SizeDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SizeDeleteRequest.Merge(m, src)
}
func (m *SizeDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_SizeDeleteRequest.Size(m)
}
func (m *SizeDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SizeDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SizeDeleteRequest proto.InternalMessageInfo

func (m *SizeDeleteRequest) GetIdentifiable() *Identifiable {
	if m != nil {
		return m.Identifiable
	}
	return nil
}

type SizeGetRequest struct {
	Identifiable         *Identifiable `protobuf:"bytes,1,opt,name=identifiable,proto3" json:"identifiable,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SizeGetRequest) Reset()         { *m = SizeGetRequest{} }
func (m *SizeGetRequest) String() string { return proto.CompactTextString(m) }
func (*SizeGetRequest) ProtoMessage()    {}
func (*SizeGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8347758cbb88e74f, []int{5}
}

func (m *SizeGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SizeGetRequest.Unmarshal(m, b)
}
func (m *SizeGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SizeGetRequest.Marshal(b, m, deterministic)
}
func (m *SizeGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SizeGetRequest.Merge(m, src)
}
func (m *SizeGetRequest) XXX_Size() int {
	return xxx_messageInfo_SizeGetRequest.Size(m)
}
func (m *SizeGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SizeGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SizeGetRequest proto.InternalMessageInfo

func (m *SizeGetRequest) GetIdentifiable() *Identifiable {
	if m != nil {
		return m.Identifiable
	}
	return nil
}

type SizeFindRequest struct {
	FindCriteria         *FindCriteria `protobuf:"bytes,1,opt,name=findCriteria,proto3" json:"findCriteria,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SizeFindRequest) Reset()         { *m = SizeFindRequest{} }
func (m *SizeFindRequest) String() string { return proto.CompactTextString(m) }
func (*SizeFindRequest) ProtoMessage()    {}
func (*SizeFindRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8347758cbb88e74f, []int{6}
}

func (m *SizeFindRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SizeFindRequest.Unmarshal(m, b)
}
func (m *SizeFindRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SizeFindRequest.Marshal(b, m, deterministic)
}
func (m *SizeFindRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SizeFindRequest.Merge(m, src)
}
func (m *SizeFindRequest) XXX_Size() int {
	return xxx_messageInfo_SizeFindRequest.Size(m)
}
func (m *SizeFindRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SizeFindRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SizeFindRequest proto.InternalMessageInfo

func (m *SizeFindRequest) GetFindCriteria() *FindCriteria {
	if m != nil {
		return m.FindCriteria
	}
	return nil
}

type SizeResponse struct {
	Size                 *Size    `protobuf:"bytes,1,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SizeResponse) Reset()         { *m = SizeResponse{} }
func (m *SizeResponse) String() string { return proto.CompactTextString(m) }
func (*SizeResponse) ProtoMessage()    {}
func (*SizeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8347758cbb88e74f, []int{7}
}

func (m *SizeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SizeResponse.Unmarshal(m, b)
}
func (m *SizeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SizeResponse.Marshal(b, m, deterministic)
}
func (m *SizeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SizeResponse.Merge(m, src)
}
func (m *SizeResponse) XXX_Size() int {
	return xxx_messageInfo_SizeResponse.Size(m)
}
func (m *SizeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SizeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SizeResponse proto.InternalMessageInfo

func (m *SizeResponse) GetSize() *Size {
	if m != nil {
		return m.Size
	}
	return nil
}

type SizeListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SizeListRequest) Reset()         { *m = SizeListRequest{} }
func (m *SizeListRequest) String() string { return proto.CompactTextString(m) }
func (*SizeListRequest) ProtoMessage()    {}
func (*SizeListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8347758cbb88e74f, []int{8}
}

func (m *SizeListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SizeListRequest.Unmarshal(m, b)
}
func (m *SizeListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SizeListRequest.Marshal(b, m, deterministic)
}
func (m *SizeListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SizeListRequest.Merge(m, src)
}
func (m *SizeListRequest) XXX_Size() int {
	return xxx_messageInfo_SizeListRequest.Size(m)
}
func (m *SizeListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SizeListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SizeListRequest proto.InternalMessageInfo

type SizeListResponse struct {
	Sizes                []*SizeResponse `protobuf:"bytes,1,rep,name=sizes,proto3" json:"sizes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SizeListResponse) Reset()         { *m = SizeListResponse{} }
func (m *SizeListResponse) String() string { return proto.CompactTextString(m) }
func (*SizeListResponse) ProtoMessage()    {}
func (*SizeListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8347758cbb88e74f, []int{9}
}

func (m *SizeListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SizeListResponse.Unmarshal(m, b)
}
func (m *SizeListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SizeListResponse.Marshal(b, m, deterministic)
}
func (m *SizeListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SizeListResponse.Merge(m, src)
}
func (m *SizeListResponse) XXX_Size() int {
	return xxx_messageInfo_SizeListResponse.Size(m)
}
func (m *SizeListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SizeListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SizeListResponse proto.InternalMessageInfo

func (m *SizeListResponse) GetSizes() []*SizeResponse {
	if m != nil {
		return m.Sizes
	}
	return nil
}

func init() {
	proto.RegisterEnum("v1.SizeConstraint_Type", SizeConstraint_Type_name, SizeConstraint_Type_value)
	proto.RegisterType((*SizeConstraint)(nil), "v1.SizeConstraint")
	proto.RegisterType((*Size)(nil), "v1.Size")
	proto.RegisterType((*SizeCreateRequest)(nil), "v1.SizeCreateRequest")
	proto.RegisterType((*SizeUpdateRequest)(nil), "v1.SizeUpdateRequest")
	proto.RegisterType((*SizeDeleteRequest)(nil), "v1.SizeDeleteRequest")
	proto.RegisterType((*SizeGetRequest)(nil), "v1.SizeGetRequest")
	proto.RegisterType((*SizeFindRequest)(nil), "v1.SizeFindRequest")
	proto.RegisterType((*SizeResponse)(nil), "v1.SizeResponse")
	proto.RegisterType((*SizeListRequest)(nil), "v1.SizeListRequest")
	proto.RegisterType((*SizeListResponse)(nil), "v1.SizeListResponse")
}

func init() { proto.RegisterFile("v1/size.proto", fileDescriptor_8347758cbb88e74f) }

var fileDescriptor_8347758cbb88e74f = []byte{
	// 499 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x94, 0xcd, 0x6e, 0xd3, 0x40,
	0x14, 0x85, 0xb1, 0xe3, 0x06, 0xb8, 0x2e, 0xad, 0x3b, 0x50, 0x61, 0x45, 0x2c, 0x2a, 0x2f, 0x50,
	0x44, 0xa9, 0x2d, 0x87, 0xae, 0xd8, 0x41, 0x48, 0xa2, 0x4a, 0x54, 0x91, 0x26, 0x65, 0x01, 0x2b,
	0x1c, 0xe7, 0xb6, 0x8c, 0x1a, 0xff, 0x60, 0x4f, 0xad, 0xb6, 0xef, 0xc0, 0x03, 0xf1, 0x76, 0x68,
	0x66, 0xec, 0x78, 0xac, 0x46, 0x02, 0x89, 0xdd, 0xe4, 0xcc, 0xf9, 0xce, 0xdc, 0xdc, 0x13, 0x05,
	0x9e, 0x55, 0x61, 0x50, 0xb2, 0x7b, 0xf4, 0xf3, 0x22, 0xe3, 0x19, 0x31, 0xab, 0x70, 0xb0, 0x5f,
	0x85, 0x41, 0x9c, 0x25, 0x49, 0x96, 0x2a, 0x71, 0x70, 0x58, 0x85, 0x01, 0x5b, 0x61, 0xca, 0xd9,
	0x25, 0x8b, 0x96, 0xeb, 0xda, 0xeb, 0xfd, 0x32, 0x60, 0x6f, 0xc1, 0xee, 0x71, 0x9c, 0xa5, 0x25,
	0x2f, 0x22, 0x96, 0x72, 0x72, 0x0c, 0x16, 0xbf, 0xcb, 0xd1, 0x35, 0x8e, 0x8c, 0xe1, 0xde, 0xe8,
	0xa5, 0x5f, 0x85, 0x7e, 0xd7, 0xe1, 0x5f, 0xdc, 0xe5, 0x48, 0xa5, 0x89, 0x38, 0xd0, 0x4b, 0x58,
	0xea, 0x9a, 0x47, 0xc6, 0xd0, 0xa2, 0xe2, 0x28, 0x95, 0xe8, 0xd6, 0xed, 0xd5, 0x4a, 0x74, 0xeb,
	0xbd, 0x01, 0x4b, 0x10, 0xe4, 0x29, 0xec, 0x8c, 0xe7, 0x74, 0xb2, 0x70, 0x1e, 0x11, 0x80, 0xfe,
	0xf9, 0xe4, 0x7c, 0x4e, 0xbf, 0x3a, 0x06, 0xb1, 0xe1, 0xf1, 0xe2, 0x62, 0x4e, 0x3f, 0xcc, 0x26,
	0x8e, 0xe9, 0x7d, 0x07, 0x4b, 0x3c, 0x46, 0x3c, 0xe8, 0xab, 0xf1, 0xe5, 0x18, 0xf6, 0x08, 0xc4,
	0x18, 0x63, 0xa9, 0xd0, 0xfa, 0x86, 0x9c, 0x82, 0x1d, 0x6f, 0x86, 0x2a, 0x5d, 0xf3, 0xa8, 0x37,
	0xb4, 0x47, 0xe4, 0xe1, 0xbc, 0x54, 0xb7, 0x79, 0x21, 0x1c, 0xc8, 0xeb, 0x02, 0x23, 0x8e, 0x14,
	0x7f, 0xde, 0x60, 0xc9, 0xc9, 0x2b, 0xb0, 0xc4, 0x02, 0xeb, 0xc7, 0x9e, 0x34, 0x19, 0x54, 0xaa,
	0x0d, 0xf2, 0x25, 0x5f, 0xfd, 0x33, 0x72, 0xa6, 0x90, 0x4f, 0xb8, 0xc6, 0x16, 0x39, 0x85, 0x5d,
	0xbd, 0x82, 0x1a, 0x75, 0x04, 0x7a, 0xa6, 0xe9, 0xb4, 0xe3, 0xf2, 0xa6, 0xaa, 0xa1, 0x19, 0xf2,
	0xff, 0xcb, 0x99, 0xc1, 0xbe, 0xc8, 0x99, 0xb2, 0x74, 0xa5, 0x05, 0x5d, 0xb2, 0x74, 0x35, 0x2e,
	0x18, 0xc7, 0x82, 0x45, 0x7a, 0xd0, 0x54, 0xd3, 0x69, 0xc7, 0xe5, 0xbd, 0x85, 0x5d, 0xf9, 0x4d,
	0xb1, 0xcc, 0xb3, 0xb4, 0xc4, 0xbf, 0x6c, 0xe2, 0x40, 0x3d, 0xfb, 0x99, 0x95, 0xcd, 0xfc, 0xde,
	0x7b, 0x70, 0x5a, 0xa9, 0x0e, 0x79, 0x0d, 0x3b, 0xc2, 0x5e, 0xba, 0x86, 0xac, 0xd1, 0xd9, 0xa4,
	0xd4, 0x06, 0xaa, 0xae, 0x47, 0xbf, 0x4d, 0xb0, 0x85, 0xbe, 0xc0, 0xa2, 0x62, 0x31, 0x92, 0x10,
	0xfa, 0xaa, 0x4a, 0x72, 0xb8, 0x69, 0x5e, 0xaf, 0x76, 0xf0, 0x20, 0x49, 0x20, 0xaa, 0xca, 0x16,
	0xe9, 0x54, 0xbb, 0x1d, 0x51, 0x55, 0xb6, 0x48, 0xa7, 0xda, 0x2d, 0xc8, 0x31, 0xf4, 0x66, 0xc8,
	0xc9, 0xe6, 0xf7, 0xd8, 0xf6, 0xb7, 0x35, 0xdf, 0x12, 0x0b, 0x27, 0xcf, 0x9b, 0x1b, 0xad, 0xa5,
	0xc1, 0x8b, 0x46, 0xec, 0x2c, 0x2c, 0x04, 0x4b, 0x7c, 0x6e, 0x11, 0x6d, 0xc3, 0xdb, 0x91, 0x8f,
	0xc1, 0xb7, 0x93, 0x2b, 0xc6, 0x7f, 0xdc, 0x2c, 0xfd, 0x38, 0x4b, 0x82, 0x04, 0x79, 0xb4, 0x3e,
	0x29, 0x79, 0x14, 0x5f, 0xd7, 0xe7, 0x28, 0x67, 0x41, 0x7e, 0x7d, 0x15, 0xc8, 0xbf, 0x86, 0xa0,
	0x0a, 0x97, 0x7d, 0x79, 0x7a, 0xf7, 0x27, 0x00, 0x00, 0xff, 0xff, 0xd7, 0x2e, 0xd1, 0xdf, 0x61,
	0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SizeServiceClient is the client API for SizeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SizeServiceClient interface {
	Create(ctx context.Context, in *SizeCreateRequest, opts ...grpc.CallOption) (*SizeResponse, error)
	Update(ctx context.Context, in *SizeUpdateRequest, opts ...grpc.CallOption) (*SizeResponse, error)
	Delete(ctx context.Context, in *SizeDeleteRequest, opts ...grpc.CallOption) (*SizeResponse, error)
	Get(ctx context.Context, in *SizeGetRequest, opts ...grpc.CallOption) (*SizeResponse, error)
	Find(ctx context.Context, in *SizeFindRequest, opts ...grpc.CallOption) (*SizeListResponse, error)
	List(ctx context.Context, in *SizeListRequest, opts ...grpc.CallOption) (*SizeListResponse, error)
}

type sizeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSizeServiceClient(cc grpc.ClientConnInterface) SizeServiceClient {
	return &sizeServiceClient{cc}
}

func (c *sizeServiceClient) Create(ctx context.Context, in *SizeCreateRequest, opts ...grpc.CallOption) (*SizeResponse, error) {
	out := new(SizeResponse)
	err := c.cc.Invoke(ctx, "/v1.SizeService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sizeServiceClient) Update(ctx context.Context, in *SizeUpdateRequest, opts ...grpc.CallOption) (*SizeResponse, error) {
	out := new(SizeResponse)
	err := c.cc.Invoke(ctx, "/v1.SizeService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sizeServiceClient) Delete(ctx context.Context, in *SizeDeleteRequest, opts ...grpc.CallOption) (*SizeResponse, error) {
	out := new(SizeResponse)
	err := c.cc.Invoke(ctx, "/v1.SizeService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sizeServiceClient) Get(ctx context.Context, in *SizeGetRequest, opts ...grpc.CallOption) (*SizeResponse, error) {
	out := new(SizeResponse)
	err := c.cc.Invoke(ctx, "/v1.SizeService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sizeServiceClient) Find(ctx context.Context, in *SizeFindRequest, opts ...grpc.CallOption) (*SizeListResponse, error) {
	out := new(SizeListResponse)
	err := c.cc.Invoke(ctx, "/v1.SizeService/Find", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sizeServiceClient) List(ctx context.Context, in *SizeListRequest, opts ...grpc.CallOption) (*SizeListResponse, error) {
	out := new(SizeListResponse)
	err := c.cc.Invoke(ctx, "/v1.SizeService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SizeServiceServer is the server API for SizeService service.
type SizeServiceServer interface {
	Create(context.Context, *SizeCreateRequest) (*SizeResponse, error)
	Update(context.Context, *SizeUpdateRequest) (*SizeResponse, error)
	Delete(context.Context, *SizeDeleteRequest) (*SizeResponse, error)
	Get(context.Context, *SizeGetRequest) (*SizeResponse, error)
	Find(context.Context, *SizeFindRequest) (*SizeListResponse, error)
	List(context.Context, *SizeListRequest) (*SizeListResponse, error)
}

// UnimplementedSizeServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSizeServiceServer struct {
}

func (*UnimplementedSizeServiceServer) Create(ctx context.Context, req *SizeCreateRequest) (*SizeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedSizeServiceServer) Update(ctx context.Context, req *SizeUpdateRequest) (*SizeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedSizeServiceServer) Delete(ctx context.Context, req *SizeDeleteRequest) (*SizeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedSizeServiceServer) Get(ctx context.Context, req *SizeGetRequest) (*SizeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedSizeServiceServer) Find(ctx context.Context, req *SizeFindRequest) (*SizeListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Find not implemented")
}
func (*UnimplementedSizeServiceServer) List(ctx context.Context, req *SizeListRequest) (*SizeListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}

func RegisterSizeServiceServer(s *grpc.Server, srv SizeServiceServer) {
	s.RegisterService(&_SizeService_serviceDesc, srv)
}

func _SizeService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SizeCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SizeServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.SizeService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SizeServiceServer).Create(ctx, req.(*SizeCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SizeService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SizeUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SizeServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.SizeService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SizeServiceServer).Update(ctx, req.(*SizeUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SizeService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SizeDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SizeServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.SizeService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SizeServiceServer).Delete(ctx, req.(*SizeDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SizeService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SizeGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SizeServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.SizeService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SizeServiceServer).Get(ctx, req.(*SizeGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SizeService_Find_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SizeFindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SizeServiceServer).Find(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.SizeService/Find",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SizeServiceServer).Find(ctx, req.(*SizeFindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SizeService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SizeListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SizeServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.SizeService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SizeServiceServer).List(ctx, req.(*SizeListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SizeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.SizeService",
	HandlerType: (*SizeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _SizeService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _SizeService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _SizeService_Delete_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _SizeService_Get_Handler,
		},
		{
			MethodName: "Find",
			Handler:    _SizeService_Find_Handler,
		},
		{
			MethodName: "List",
			Handler:    _SizeService_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/size.proto",
}
