// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.20.0
// 	protoc        v3.11.4
// source: v1/size.proto

package v1

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type SizeConstraint_Type int32

const (
	SizeConstraint_CORES   SizeConstraint_Type = 0
	SizeConstraint_MEMORY  SizeConstraint_Type = 1
	SizeConstraint_STORAGE SizeConstraint_Type = 2
)

// Enum value maps for SizeConstraint_Type.
var (
	SizeConstraint_Type_name = map[int32]string{
		0: "CORES",
		1: "MEMORY",
		2: "STORAGE",
	}
	SizeConstraint_Type_value = map[string]int32{
		"CORES":   0,
		"MEMORY":  1,
		"STORAGE": 2,
	}
)

func (x SizeConstraint_Type) Enum() *SizeConstraint_Type {
	p := new(SizeConstraint_Type)
	*p = x
	return p
}

func (x SizeConstraint_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SizeConstraint_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_size_proto_enumTypes[0].Descriptor()
}

func (SizeConstraint_Type) Type() protoreflect.EnumType {
	return &file_v1_size_proto_enumTypes[0]
}

func (x SizeConstraint_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SizeConstraint_Type.Descriptor instead.
func (SizeConstraint_Type) EnumDescriptor() ([]byte, []int) {
	return file_v1_size_proto_rawDescGZIP(), []int{0, 0}
}

// a machine matches to a size in order to make them easier to categorize
type SizeConstraint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type SizeConstraint_Type `protobuf:"varint,1,opt,name=type,proto3,enum=v1.SizeConstraint_Type" json:"type,omitempty"` // the type of the constraint, default CORES
	Min  uint64              `protobuf:"varint,2,opt,name=min,proto3" json:"min,omitempty"`                               // the minimum value of the constraint
	Max  uint64              `protobuf:"varint,3,opt,name=max,proto3" json:"max,omitempty"`                               // the maximum value of the constraint
}

func (x *SizeConstraint) Reset() {
	*x = SizeConstraint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_size_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SizeConstraint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SizeConstraint) ProtoMessage() {}

func (x *SizeConstraint) ProtoReflect() protoreflect.Message {
	mi := &file_v1_size_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SizeConstraint.ProtoReflect.Descriptor instead.
func (*SizeConstraint) Descriptor() ([]byte, []int) {
	return file_v1_size_proto_rawDescGZIP(), []int{0}
}

func (x *SizeConstraint) GetType() SizeConstraint_Type {
	if x != nil {
		return x.Type
	}
	return SizeConstraint_CORES
}

func (x *SizeConstraint) GetMin() uint64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *SizeConstraint) GetMax() uint64 {
	if x != nil {
		return x.Max
	}
	return 0
}

type Size struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Common      *Common           `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	Constraints []*SizeConstraint `protobuf:"bytes,2,rep,name=constraints,proto3" json:"constraints,omitempty"` // a list of constraints that defines this size
}

func (x *Size) Reset() {
	*x = Size{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_size_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Size) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Size) ProtoMessage() {}

func (x *Size) ProtoReflect() protoreflect.Message {
	mi := &file_v1_size_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Size.ProtoReflect.Descriptor instead.
func (*Size) Descriptor() ([]byte, []int) {
	return file_v1_size_proto_rawDescGZIP(), []int{1}
}

func (x *Size) GetCommon() *Common {
	if x != nil {
		return x.Common
	}
	return nil
}

func (x *Size) GetConstraints() []*SizeConstraint {
	if x != nil {
		return x.Constraints
	}
	return nil
}

type SizeCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Size *Size `protobuf:"bytes,1,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *SizeCreateRequest) Reset() {
	*x = SizeCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_size_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SizeCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SizeCreateRequest) ProtoMessage() {}

func (x *SizeCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_size_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SizeCreateRequest.ProtoReflect.Descriptor instead.
func (*SizeCreateRequest) Descriptor() ([]byte, []int) {
	return file_v1_size_proto_rawDescGZIP(), []int{2}
}

func (x *SizeCreateRequest) GetSize() *Size {
	if x != nil {
		return x.Size
	}
	return nil
}

type SizeUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Size *Size `protobuf:"bytes,1,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *SizeUpdateRequest) Reset() {
	*x = SizeUpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_size_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SizeUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SizeUpdateRequest) ProtoMessage() {}

func (x *SizeUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_size_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SizeUpdateRequest.ProtoReflect.Descriptor instead.
func (*SizeUpdateRequest) Descriptor() ([]byte, []int) {
	return file_v1_size_proto_rawDescGZIP(), []int{3}
}

func (x *SizeUpdateRequest) GetSize() *Size {
	if x != nil {
		return x.Size
	}
	return nil
}

type SizeDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Identifiable *Identifiable `protobuf:"bytes,1,opt,name=identifiable,proto3" json:"identifiable,omitempty"`
}

func (x *SizeDeleteRequest) Reset() {
	*x = SizeDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_size_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SizeDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SizeDeleteRequest) ProtoMessage() {}

func (x *SizeDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_size_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SizeDeleteRequest.ProtoReflect.Descriptor instead.
func (*SizeDeleteRequest) Descriptor() ([]byte, []int) {
	return file_v1_size_proto_rawDescGZIP(), []int{4}
}

func (x *SizeDeleteRequest) GetIdentifiable() *Identifiable {
	if x != nil {
		return x.Identifiable
	}
	return nil
}

type SizeGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Identifiable *Identifiable `protobuf:"bytes,1,opt,name=identifiable,proto3" json:"identifiable,omitempty"`
}

func (x *SizeGetRequest) Reset() {
	*x = SizeGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_size_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SizeGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SizeGetRequest) ProtoMessage() {}

func (x *SizeGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_size_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SizeGetRequest.ProtoReflect.Descriptor instead.
func (*SizeGetRequest) Descriptor() ([]byte, []int) {
	return file_v1_size_proto_rawDescGZIP(), []int{5}
}

func (x *SizeGetRequest) GetIdentifiable() *Identifiable {
	if x != nil {
		return x.Identifiable
	}
	return nil
}

type SizeFindRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FindCriteria *FindCriteria `protobuf:"bytes,1,opt,name=findCriteria,proto3" json:"findCriteria,omitempty"`
}

func (x *SizeFindRequest) Reset() {
	*x = SizeFindRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_size_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SizeFindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SizeFindRequest) ProtoMessage() {}

func (x *SizeFindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_size_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SizeFindRequest.ProtoReflect.Descriptor instead.
func (*SizeFindRequest) Descriptor() ([]byte, []int) {
	return file_v1_size_proto_rawDescGZIP(), []int{6}
}

func (x *SizeFindRequest) GetFindCriteria() *FindCriteria {
	if x != nil {
		return x.FindCriteria
	}
	return nil
}

type SizeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Size *Size `protobuf:"bytes,1,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *SizeResponse) Reset() {
	*x = SizeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_size_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SizeResponse) ProtoMessage() {}

func (x *SizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_size_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SizeResponse.ProtoReflect.Descriptor instead.
func (*SizeResponse) Descriptor() ([]byte, []int) {
	return file_v1_size_proto_rawDescGZIP(), []int{7}
}

func (x *SizeResponse) GetSize() *Size {
	if x != nil {
		return x.Size
	}
	return nil
}

type SizeListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SizeListRequest) Reset() {
	*x = SizeListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_size_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SizeListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SizeListRequest) ProtoMessage() {}

func (x *SizeListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_size_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SizeListRequest.ProtoReflect.Descriptor instead.
func (*SizeListRequest) Descriptor() ([]byte, []int) {
	return file_v1_size_proto_rawDescGZIP(), []int{8}
}

type SizeListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sizes []*Size `protobuf:"bytes,1,rep,name=sizes,proto3" json:"sizes,omitempty"`
}

func (x *SizeListResponse) Reset() {
	*x = SizeListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_size_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SizeListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SizeListResponse) ProtoMessage() {}

func (x *SizeListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_size_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SizeListResponse.ProtoReflect.Descriptor instead.
func (*SizeListResponse) Descriptor() ([]byte, []int) {
	return file_v1_size_proto_rawDescGZIP(), []int{9}
}

func (x *SizeListResponse) GetSizes() []*Size {
	if x != nil {
		return x.Sizes
	}
	return nil
}

var File_v1_size_proto protoreflect.FileDescriptor

var file_v1_size_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x76, 0x31, 0x2f, 0x73, 0x69, 0x7a, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x02, 0x76, 0x31, 0x1a, 0x0f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x15, 0x76, 0x31, 0x2f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66,
	0x69, 0x61, 0x62, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8d, 0x01, 0x0a, 0x0e,
	0x53, 0x69, 0x7a, 0x65, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x12, 0x2b,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x76,
	0x31, 0x2e, 0x53, 0x69, 0x7a, 0x65, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74,
	0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d,
	0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x6d, 0x69, 0x6e, 0x12, 0x10, 0x0a,
	0x03, 0x6d, 0x61, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x6d, 0x61, 0x78, 0x22,
	0x2a, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x43, 0x4f, 0x52, 0x45, 0x53,
	0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x4d, 0x45, 0x4d, 0x4f, 0x52, 0x59, 0x10, 0x01, 0x12, 0x0b,
	0x0a, 0x07, 0x53, 0x54, 0x4f, 0x52, 0x41, 0x47, 0x45, 0x10, 0x02, 0x22, 0x60, 0x0a, 0x04, 0x53,
	0x69, 0x7a, 0x65, 0x12, 0x22, 0x0a, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52,
	0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x12, 0x34, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x73, 0x74,
	0x72, 0x61, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x76,
	0x31, 0x2e, 0x53, 0x69, 0x7a, 0x65, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74,
	0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x73, 0x22, 0x31, 0x0a,
	0x11, 0x53, 0x69, 0x7a, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1c, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x08, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x69, 0x7a, 0x65, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65,
	0x22, 0x31, 0x0a, 0x11, 0x53, 0x69, 0x7a, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x69, 0x7a, 0x65, 0x52, 0x04, 0x73,
	0x69, 0x7a, 0x65, 0x22, 0x49, 0x0a, 0x11, 0x53, 0x69, 0x7a, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x34, 0x0a, 0x0c, 0x69, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x66, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x76, 0x31, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x61, 0x62, 0x6c, 0x65,
	0x52, 0x0c, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x22, 0x46,
	0x0a, 0x0e, 0x53, 0x69, 0x7a, 0x65, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x34, 0x0a, 0x0c, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x61, 0x62, 0x6c, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x66, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x0c, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x66, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x22, 0x47, 0x0a, 0x0f, 0x53, 0x69, 0x7a, 0x65, 0x46, 0x69,
	0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x34, 0x0a, 0x0c, 0x66, 0x69, 0x6e,
	0x64, 0x43, 0x72, 0x69, 0x74, 0x65, 0x72, 0x69, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x43, 0x72, 0x69, 0x74, 0x65, 0x72, 0x69,
	0x61, 0x52, 0x0c, 0x66, 0x69, 0x6e, 0x64, 0x43, 0x72, 0x69, 0x74, 0x65, 0x72, 0x69, 0x61, 0x22,
	0x2c, 0x0a, 0x0c, 0x53, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1c, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e,
	0x76, 0x31, 0x2e, 0x53, 0x69, 0x7a, 0x65, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x22, 0x11, 0x0a,
	0x0f, 0x53, 0x69, 0x7a, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x32, 0x0a, 0x10, 0x53, 0x69, 0x7a, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x05, 0x73, 0x69, 0x7a, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x69, 0x7a, 0x65, 0x52, 0x05, 0x73,
	0x69, 0x7a, 0x65, 0x73, 0x32, 0xb9, 0x02, 0x0a, 0x0b, 0x53, 0x69, 0x7a, 0x65, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x31, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x15,
	0x2e, 0x76, 0x31, 0x2e, 0x53, 0x69, 0x7a, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x69, 0x7a, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x12, 0x15, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x69, 0x7a, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x69,
	0x7a, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x06, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x12, 0x15, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x69, 0x7a, 0x65, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x76, 0x31,
	0x2e, 0x53, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a,
	0x03, 0x47, 0x65, 0x74, 0x12, 0x12, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x69, 0x7a, 0x65, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x69,
	0x7a, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x04, 0x46, 0x69,
	0x6e, 0x64, 0x12, 0x13, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x69, 0x7a, 0x65, 0x46, 0x69, 0x6e, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x69, 0x7a,
	0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a,
	0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x13, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x69, 0x7a, 0x65, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x76, 0x31, 0x2e,
	0x53, 0x69, 0x7a, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d,
	0x65, 0x74, 0x61, 0x6c, 0x2d, 0x73, 0x74, 0x61, 0x63, 0x6b, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x6c,
	0x2d, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76,
	0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1_size_proto_rawDescOnce sync.Once
	file_v1_size_proto_rawDescData = file_v1_size_proto_rawDesc
)

func file_v1_size_proto_rawDescGZIP() []byte {
	file_v1_size_proto_rawDescOnce.Do(func() {
		file_v1_size_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_size_proto_rawDescData)
	})
	return file_v1_size_proto_rawDescData
}

var file_v1_size_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_size_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_v1_size_proto_goTypes = []interface{}{
	(SizeConstraint_Type)(0),  // 0: v1.SizeConstraint.Type
	(*SizeConstraint)(nil),    // 1: v1.SizeConstraint
	(*Size)(nil),              // 2: v1.Size
	(*SizeCreateRequest)(nil), // 3: v1.SizeCreateRequest
	(*SizeUpdateRequest)(nil), // 4: v1.SizeUpdateRequest
	(*SizeDeleteRequest)(nil), // 5: v1.SizeDeleteRequest
	(*SizeGetRequest)(nil),    // 6: v1.SizeGetRequest
	(*SizeFindRequest)(nil),   // 7: v1.SizeFindRequest
	(*SizeResponse)(nil),      // 8: v1.SizeResponse
	(*SizeListRequest)(nil),   // 9: v1.SizeListRequest
	(*SizeListResponse)(nil),  // 10: v1.SizeListResponse
	(*Common)(nil),            // 11: v1.Common
	(*Identifiable)(nil),      // 12: v1.Identifiable
	(*FindCriteria)(nil),      // 13: v1.FindCriteria
}
var file_v1_size_proto_depIdxs = []int32{
	0,  // 0: v1.SizeConstraint.type:type_name -> v1.SizeConstraint.Type
	11, // 1: v1.Size.common:type_name -> v1.Common
	1,  // 2: v1.Size.constraints:type_name -> v1.SizeConstraint
	2,  // 3: v1.SizeCreateRequest.size:type_name -> v1.Size
	2,  // 4: v1.SizeUpdateRequest.size:type_name -> v1.Size
	12, // 5: v1.SizeDeleteRequest.identifiable:type_name -> v1.Identifiable
	12, // 6: v1.SizeGetRequest.identifiable:type_name -> v1.Identifiable
	13, // 7: v1.SizeFindRequest.findCriteria:type_name -> v1.FindCriteria
	2,  // 8: v1.SizeResponse.size:type_name -> v1.Size
	2,  // 9: v1.SizeListResponse.sizes:type_name -> v1.Size
	3,  // 10: v1.SizeService.Create:input_type -> v1.SizeCreateRequest
	4,  // 11: v1.SizeService.Update:input_type -> v1.SizeUpdateRequest
	5,  // 12: v1.SizeService.Delete:input_type -> v1.SizeDeleteRequest
	6,  // 13: v1.SizeService.Get:input_type -> v1.SizeGetRequest
	7,  // 14: v1.SizeService.Find:input_type -> v1.SizeFindRequest
	9,  // 15: v1.SizeService.List:input_type -> v1.SizeListRequest
	8,  // 16: v1.SizeService.Create:output_type -> v1.SizeResponse
	8,  // 17: v1.SizeService.Update:output_type -> v1.SizeResponse
	8,  // 18: v1.SizeService.Delete:output_type -> v1.SizeResponse
	8,  // 19: v1.SizeService.Get:output_type -> v1.SizeResponse
	10, // 20: v1.SizeService.Find:output_type -> v1.SizeListResponse
	10, // 21: v1.SizeService.List:output_type -> v1.SizeListResponse
	16, // [16:22] is the sub-list for method output_type
	10, // [10:16] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_v1_size_proto_init() }
func file_v1_size_proto_init() {
	if File_v1_size_proto != nil {
		return
	}
	file_v1_common_proto_init()
	file_v1_identifiable_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_v1_size_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SizeConstraint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_size_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Size); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_size_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SizeCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_size_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SizeUpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_size_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SizeDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_size_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SizeGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_size_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SizeFindRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_size_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SizeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_size_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SizeListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_size_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SizeListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_size_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_size_proto_goTypes,
		DependencyIndexes: file_v1_size_proto_depIdxs,
		EnumInfos:         file_v1_size_proto_enumTypes,
		MessageInfos:      file_v1_size_proto_msgTypes,
	}.Build()
	File_v1_size_proto = out.File
	file_v1_size_proto_rawDesc = nil
	file_v1_size_proto_goTypes = nil
	file_v1_size_proto_depIdxs = nil
}
