// Code generated by protoc-gen-go. DO NOT EDIT.
// source: v1/switch.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BGPFilter struct {
	CIDRs                []string                `protobuf:"bytes,1,rep,name=CIDRs,proto3" json:"CIDRs,omitempty"`
	VNIs                 []*wrappers.StringValue `protobuf:"bytes,2,rep,name=VNIs,proto3" json:"VNIs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *BGPFilter) Reset()         { *m = BGPFilter{} }
func (m *BGPFilter) String() string { return proto.CompactTextString(m) }
func (*BGPFilter) ProtoMessage()    {}
func (*BGPFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_4559081f66c40988, []int{0}
}

func (m *BGPFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BGPFilter.Unmarshal(m, b)
}
func (m *BGPFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BGPFilter.Marshal(b, m, deterministic)
}
func (m *BGPFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BGPFilter.Merge(m, src)
}
func (m *BGPFilter) XXX_Size() int {
	return xxx_messageInfo_BGPFilter.Size(m)
}
func (m *BGPFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_BGPFilter.DiscardUnknown(m)
}

var xxx_messageInfo_BGPFilter proto.InternalMessageInfo

func (m *BGPFilter) GetCIDRs() []string {
	if m != nil {
		return m.CIDRs
	}
	return nil
}

func (m *BGPFilter) GetVNIs() []*wrappers.StringValue {
	if m != nil {
		return m.VNIs
	}
	return nil
}

type SwitchNic struct {
	MacAddress           string                `protobuf:"bytes,1,opt,name=macAddress,proto3" json:"macAddress,omitempty"`
	Name                 string                `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Vrf                  *wrappers.StringValue `protobuf:"bytes,3,opt,name=vrf,proto3" json:"vrf,omitempty"`
	BGPFilter            *BGPFilter            `protobuf:"bytes,4,opt,name=BGPFilter,proto3" json:"BGPFilter,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *SwitchNic) Reset()         { *m = SwitchNic{} }
func (m *SwitchNic) String() string { return proto.CompactTextString(m) }
func (*SwitchNic) ProtoMessage()    {}
func (*SwitchNic) Descriptor() ([]byte, []int) {
	return fileDescriptor_4559081f66c40988, []int{1}
}

func (m *SwitchNic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SwitchNic.Unmarshal(m, b)
}
func (m *SwitchNic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SwitchNic.Marshal(b, m, deterministic)
}
func (m *SwitchNic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SwitchNic.Merge(m, src)
}
func (m *SwitchNic) XXX_Size() int {
	return xxx_messageInfo_SwitchNic.Size(m)
}
func (m *SwitchNic) XXX_DiscardUnknown() {
	xxx_messageInfo_SwitchNic.DiscardUnknown(m)
}

var xxx_messageInfo_SwitchNic proto.InternalMessageInfo

func (m *SwitchNic) GetMacAddress() string {
	if m != nil {
		return m.MacAddress
	}
	return ""
}

func (m *SwitchNic) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SwitchNic) GetVrf() *wrappers.StringValue {
	if m != nil {
		return m.Vrf
	}
	return nil
}

func (m *SwitchNic) GetBGPFilter() *BGPFilter {
	if m != nil {
		return m.BGPFilter
	}
	return nil
}

type SwitchConnection struct {
	Nic                  string                `protobuf:"bytes,1,opt,name=nic,proto3" json:"nic,omitempty"`
	MachineID            *wrappers.StringValue `protobuf:"bytes,2,opt,name=machineID,proto3" json:"machineID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *SwitchConnection) Reset()         { *m = SwitchConnection{} }
func (m *SwitchConnection) String() string { return proto.CompactTextString(m) }
func (*SwitchConnection) ProtoMessage()    {}
func (*SwitchConnection) Descriptor() ([]byte, []int) {
	return fileDescriptor_4559081f66c40988, []int{2}
}

func (m *SwitchConnection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SwitchConnection.Unmarshal(m, b)
}
func (m *SwitchConnection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SwitchConnection.Marshal(b, m, deterministic)
}
func (m *SwitchConnection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SwitchConnection.Merge(m, src)
}
func (m *SwitchConnection) XXX_Size() int {
	return xxx_messageInfo_SwitchConnection.Size(m)
}
func (m *SwitchConnection) XXX_DiscardUnknown() {
	xxx_messageInfo_SwitchConnection.DiscardUnknown(m)
}

var xxx_messageInfo_SwitchConnection proto.InternalMessageInfo

func (m *SwitchConnection) GetNic() string {
	if m != nil {
		return m.Nic
	}
	return ""
}

func (m *SwitchConnection) GetMachineID() *wrappers.StringValue {
	if m != nil {
		return m.MachineID
	}
	return nil
}

// A switch that can register at the api
type Switch struct {
	Common               *Common      `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	RackID               string       `protobuf:"bytes,2,opt,name=rackID,proto3" json:"rackID,omitempty"`
	Nics                 []*SwitchNic `protobuf:"bytes,3,rep,name=nics,proto3" json:"nics,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Switch) Reset()         { *m = Switch{} }
func (m *Switch) String() string { return proto.CompactTextString(m) }
func (*Switch) ProtoMessage()    {}
func (*Switch) Descriptor() ([]byte, []int) {
	return fileDescriptor_4559081f66c40988, []int{3}
}

func (m *Switch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Switch.Unmarshal(m, b)
}
func (m *Switch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Switch.Marshal(b, m, deterministic)
}
func (m *Switch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Switch.Merge(m, src)
}
func (m *Switch) XXX_Size() int {
	return xxx_messageInfo_Switch.Size(m)
}
func (m *Switch) XXX_DiscardUnknown() {
	xxx_messageInfo_Switch.DiscardUnknown(m)
}

var xxx_messageInfo_Switch proto.InternalMessageInfo

func (m *Switch) GetCommon() *Common {
	if m != nil {
		return m.Common
	}
	return nil
}

func (m *Switch) GetRackID() string {
	if m != nil {
		return m.RackID
	}
	return ""
}

func (m *Switch) GetNics() []*SwitchNic {
	if m != nil {
		return m.Nics
	}
	return nil
}

type SwitchRegisterRequest struct {
	Switch               *Switch  `protobuf:"bytes,1,opt,name=switch,proto3" json:"switch,omitempty"`
	PartitionID          string   `protobuf:"bytes,2,opt,name=partitionID,proto3" json:"partitionID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SwitchRegisterRequest) Reset()         { *m = SwitchRegisterRequest{} }
func (m *SwitchRegisterRequest) String() string { return proto.CompactTextString(m) }
func (*SwitchRegisterRequest) ProtoMessage()    {}
func (*SwitchRegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4559081f66c40988, []int{4}
}

func (m *SwitchRegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SwitchRegisterRequest.Unmarshal(m, b)
}
func (m *SwitchRegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SwitchRegisterRequest.Marshal(b, m, deterministic)
}
func (m *SwitchRegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SwitchRegisterRequest.Merge(m, src)
}
func (m *SwitchRegisterRequest) XXX_Size() int {
	return xxx_messageInfo_SwitchRegisterRequest.Size(m)
}
func (m *SwitchRegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SwitchRegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SwitchRegisterRequest proto.InternalMessageInfo

func (m *SwitchRegisterRequest) GetSwitch() *Switch {
	if m != nil {
		return m.Switch
	}
	return nil
}

func (m *SwitchRegisterRequest) GetPartitionID() string {
	if m != nil {
		return m.PartitionID
	}
	return ""
}

type SwitchGetRequest struct {
	Identifiable         *Identifiable `protobuf:"bytes,1,opt,name=identifiable,proto3" json:"identifiable,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SwitchGetRequest) Reset()         { *m = SwitchGetRequest{} }
func (m *SwitchGetRequest) String() string { return proto.CompactTextString(m) }
func (*SwitchGetRequest) ProtoMessage()    {}
func (*SwitchGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4559081f66c40988, []int{5}
}

func (m *SwitchGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SwitchGetRequest.Unmarshal(m, b)
}
func (m *SwitchGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SwitchGetRequest.Marshal(b, m, deterministic)
}
func (m *SwitchGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SwitchGetRequest.Merge(m, src)
}
func (m *SwitchGetRequest) XXX_Size() int {
	return xxx_messageInfo_SwitchGetRequest.Size(m)
}
func (m *SwitchGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SwitchGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SwitchGetRequest proto.InternalMessageInfo

func (m *SwitchGetRequest) GetIdentifiable() *Identifiable {
	if m != nil {
		return m.Identifiable
	}
	return nil
}

type SwitchFindRequest struct {
	FindCriteria         *FindCriteria `protobuf:"bytes,1,opt,name=findCriteria,proto3" json:"findCriteria,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SwitchFindRequest) Reset()         { *m = SwitchFindRequest{} }
func (m *SwitchFindRequest) String() string { return proto.CompactTextString(m) }
func (*SwitchFindRequest) ProtoMessage()    {}
func (*SwitchFindRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4559081f66c40988, []int{6}
}

func (m *SwitchFindRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SwitchFindRequest.Unmarshal(m, b)
}
func (m *SwitchFindRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SwitchFindRequest.Marshal(b, m, deterministic)
}
func (m *SwitchFindRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SwitchFindRequest.Merge(m, src)
}
func (m *SwitchFindRequest) XXX_Size() int {
	return xxx_messageInfo_SwitchFindRequest.Size(m)
}
func (m *SwitchFindRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SwitchFindRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SwitchFindRequest proto.InternalMessageInfo

func (m *SwitchFindRequest) GetFindCriteria() *FindCriteria {
	if m != nil {
		return m.FindCriteria
	}
	return nil
}

type SwitchResponse struct {
	Switch               *Switch             `protobuf:"bytes,1,opt,name=switch,proto3" json:"switch,omitempty"`
	Connections          []*SwitchConnection `protobuf:"bytes,2,rep,name=connections,proto3" json:"connections,omitempty"`
	Partition            *PartitionResponse  `protobuf:"bytes,3,opt,name=partition,proto3" json:"partition,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *SwitchResponse) Reset()         { *m = SwitchResponse{} }
func (m *SwitchResponse) String() string { return proto.CompactTextString(m) }
func (*SwitchResponse) ProtoMessage()    {}
func (*SwitchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4559081f66c40988, []int{7}
}

func (m *SwitchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SwitchResponse.Unmarshal(m, b)
}
func (m *SwitchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SwitchResponse.Marshal(b, m, deterministic)
}
func (m *SwitchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SwitchResponse.Merge(m, src)
}
func (m *SwitchResponse) XXX_Size() int {
	return xxx_messageInfo_SwitchResponse.Size(m)
}
func (m *SwitchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SwitchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SwitchResponse proto.InternalMessageInfo

func (m *SwitchResponse) GetSwitch() *Switch {
	if m != nil {
		return m.Switch
	}
	return nil
}

func (m *SwitchResponse) GetConnections() []*SwitchConnection {
	if m != nil {
		return m.Connections
	}
	return nil
}

func (m *SwitchResponse) GetPartition() *PartitionResponse {
	if m != nil {
		return m.Partition
	}
	return nil
}

type SwitchListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SwitchListRequest) Reset()         { *m = SwitchListRequest{} }
func (m *SwitchListRequest) String() string { return proto.CompactTextString(m) }
func (*SwitchListRequest) ProtoMessage()    {}
func (*SwitchListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4559081f66c40988, []int{8}
}

func (m *SwitchListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SwitchListRequest.Unmarshal(m, b)
}
func (m *SwitchListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SwitchListRequest.Marshal(b, m, deterministic)
}
func (m *SwitchListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SwitchListRequest.Merge(m, src)
}
func (m *SwitchListRequest) XXX_Size() int {
	return xxx_messageInfo_SwitchListRequest.Size(m)
}
func (m *SwitchListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SwitchListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SwitchListRequest proto.InternalMessageInfo

type SwitchListResponse struct {
	Switches             []*Switch `protobuf:"bytes,1,rep,name=switches,proto3" json:"switches,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SwitchListResponse) Reset()         { *m = SwitchListResponse{} }
func (m *SwitchListResponse) String() string { return proto.CompactTextString(m) }
func (*SwitchListResponse) ProtoMessage()    {}
func (*SwitchListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4559081f66c40988, []int{9}
}

func (m *SwitchListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SwitchListResponse.Unmarshal(m, b)
}
func (m *SwitchListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SwitchListResponse.Marshal(b, m, deterministic)
}
func (m *SwitchListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SwitchListResponse.Merge(m, src)
}
func (m *SwitchListResponse) XXX_Size() int {
	return xxx_messageInfo_SwitchListResponse.Size(m)
}
func (m *SwitchListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SwitchListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SwitchListResponse proto.InternalMessageInfo

func (m *SwitchListResponse) GetSwitches() []*Switch {
	if m != nil {
		return m.Switches
	}
	return nil
}

func init() {
	proto.RegisterType((*BGPFilter)(nil), "v1.BGPFilter")
	proto.RegisterType((*SwitchNic)(nil), "v1.SwitchNic")
	proto.RegisterType((*SwitchConnection)(nil), "v1.SwitchConnection")
	proto.RegisterType((*Switch)(nil), "v1.Switch")
	proto.RegisterType((*SwitchRegisterRequest)(nil), "v1.SwitchRegisterRequest")
	proto.RegisterType((*SwitchGetRequest)(nil), "v1.SwitchGetRequest")
	proto.RegisterType((*SwitchFindRequest)(nil), "v1.SwitchFindRequest")
	proto.RegisterType((*SwitchResponse)(nil), "v1.SwitchResponse")
	proto.RegisterType((*SwitchListRequest)(nil), "v1.SwitchListRequest")
	proto.RegisterType((*SwitchListResponse)(nil), "v1.SwitchListResponse")
}

func init() { proto.RegisterFile("v1/switch.proto", fileDescriptor_4559081f66c40988) }

var fileDescriptor_4559081f66c40988 = []byte{
	// 611 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x5f, 0x6b, 0x13, 0x4f,
	0x14, 0x25, 0xdd, 0xfc, 0xc2, 0x6f, 0x6f, 0xac, 0xd6, 0xb1, 0x29, 0x31, 0x48, 0x89, 0xfb, 0x20,
	0x05, 0xe9, 0xae, 0x69, 0xad, 0x82, 0xf8, 0x62, 0x53, 0x5a, 0x03, 0x52, 0xca, 0x04, 0xfb, 0x20,
	0x08, 0x4e, 0x66, 0x27, 0xdb, 0xa1, 0xd9, 0x3f, 0xee, 0x4c, 0xb6, 0x5f, 0xc6, 0x17, 0x3f, 0x9d,
	0x5f, 0x43, 0xe6, 0xcf, 0xee, 0x4e, 0x40, 0xa9, 0x6f, 0x33, 0xe7, 0xde, 0x7b, 0xee, 0x39, 0x77,
	0xee, 0x2e, 0x3c, 0xaa, 0x26, 0x91, 0xb8, 0xe3, 0x92, 0xde, 0x84, 0x45, 0x99, 0xcb, 0x1c, 0x6d,
	0x55, 0x93, 0x91, 0x02, 0x69, 0x9e, 0xa6, 0x79, 0x66, 0xc0, 0x11, 0xaa, 0x26, 0x51, 0x41, 0x4a,
	0xc9, 0x25, 0x6f, 0xb0, 0x41, 0x35, 0x89, 0x78, 0xcc, 0x32, 0xc9, 0x97, 0x9c, 0x2c, 0x56, 0xcc,
	0xc2, 0xfb, 0x49, 0x9e, 0x27, 0x2b, 0x16, 0xe9, 0xdb, 0x62, 0xbd, 0x8c, 0xee, 0x4a, 0x52, 0x14,
	0xac, 0x14, 0x26, 0x1e, 0xcc, 0xc1, 0x3f, 0xbd, 0xb8, 0x3a, 0xe7, 0x2b, 0xc9, 0x4a, 0xb4, 0x0b,
	0xff, 0x4d, 0x67, 0x67, 0x58, 0x0c, 0x3b, 0x63, 0xef, 0xc0, 0xc7, 0xe6, 0x82, 0x5e, 0x41, 0xf7,
	0xfa, 0x72, 0x26, 0x86, 0x5b, 0x63, 0xef, 0xa0, 0x7f, 0xf4, 0x2c, 0x34, 0x8c, 0x61, 0xcd, 0x18,
	0xce, 0x65, 0xc9, 0xb3, 0xe4, 0x9a, 0xac, 0xd6, 0x0c, 0xeb, 0xcc, 0xe0, 0x47, 0x07, 0xfc, 0xb9,
	0x76, 0x71, 0xc9, 0x29, 0xda, 0x07, 0x48, 0x09, 0xfd, 0x10, 0xc7, 0x25, 0x13, 0x8a, 0xba, 0x73,
	0xe0, 0x63, 0x07, 0x41, 0x08, 0xba, 0x19, 0x49, 0xd9, 0x70, 0x4b, 0x47, 0xf4, 0x19, 0x85, 0xe0,
	0x55, 0xe5, 0x72, 0xe8, 0x8d, 0x3b, 0xf7, 0xb6, 0x54, 0x89, 0xe8, 0xa5, 0x63, 0x63, 0xd8, 0xd5,
	0x55, 0xdb, 0x61, 0x35, 0x09, 0x1b, 0x10, 0xb7, 0xf1, 0xe0, 0x1b, 0xec, 0x18, 0x75, 0xd3, 0x3c,
	0xcb, 0x18, 0x55, 0x43, 0x44, 0x3b, 0xe0, 0x65, 0x9c, 0x5a, 0x75, 0xea, 0x88, 0xde, 0x81, 0x9f,
	0x12, 0x7a, 0xc3, 0x33, 0x36, 0x3b, 0xd3, 0xda, 0xee, 0x13, 0xd2, 0xa6, 0x07, 0x09, 0xf4, 0x4c,
	0x07, 0x14, 0x40, 0xcf, 0x3c, 0x9d, 0xa6, 0xee, 0x1f, 0x81, 0x52, 0x35, 0xd5, 0x08, 0xb6, 0x11,
	0xb4, 0x07, 0xbd, 0x92, 0xd0, 0x5b, 0xdb, 0xc6, 0xc7, 0xf6, 0x86, 0x9e, 0x43, 0x37, 0xe3, 0x54,
	0x0c, 0x3d, 0x3d, 0x78, 0xed, 0xa7, 0x99, 0x2a, 0xd6, 0xa1, 0xe0, 0x2b, 0x0c, 0x0c, 0x84, 0x59,
	0xc2, 0x85, 0xf2, 0xc9, 0xbe, 0xaf, 0x99, 0x90, 0xaa, 0xaf, 0xd9, 0x23, 0xb7, 0xaf, 0x4d, 0xb5,
	0x11, 0x34, 0x86, 0x7e, 0xb3, 0x45, 0x4d, 0x73, 0x17, 0x0a, 0x3e, 0xd6, 0x93, 0xba, 0x60, 0xb2,
	0x66, 0x7e, 0x0d, 0x0f, 0xdc, 0x3d, 0xb3, 0xfc, 0x3b, 0x8a, 0x7f, 0xe6, 0xe0, 0x78, 0x23, 0x2b,
	0x98, 0xc1, 0x63, 0xc3, 0x74, 0xce, 0xb3, 0xd8, 0xa1, 0x5a, 0xf2, 0x2c, 0x9e, 0x96, 0x5c, 0xb2,
	0x92, 0x13, 0x97, 0xea, 0xdc, 0xc1, 0xf1, 0x46, 0x56, 0xf0, 0xb3, 0x03, 0x0f, 0x6b, 0xd3, 0xa2,
	0xc8, 0x33, 0xc1, 0xfe, 0xc9, 0xed, 0x1b, 0xe8, 0xd3, 0xe6, 0xbd, 0xeb, 0x6d, 0xde, 0x6d, 0x13,
	0xdb, 0x65, 0xc0, 0x6e, 0x22, 0x3a, 0x06, 0xbf, 0x19, 0x89, 0x5d, 0xc8, 0x81, 0xaa, 0xba, 0xaa,
	0xc1, 0x5a, 0x05, 0x6e, 0xf3, 0x82, 0x27, 0xb5, 0xdd, 0x4f, 0x5c, 0xd4, 0x93, 0x0b, 0xde, 0x03,
	0x72, 0x41, 0xab, 0xfd, 0x05, 0xfc, 0x6f, 0x14, 0x32, 0xf3, 0xdd, 0x6d, 0xaa, 0x6f, 0x62, 0x47,
	0xbf, 0x3a, 0xb0, 0x6d, 0xc0, 0x39, 0x2b, 0x2b, 0x4e, 0x19, 0x7a, 0x0b, 0xbd, 0xcf, 0x45, 0x4c,
	0x24, 0x43, 0x4f, 0x9d, 0x8a, 0xcd, 0x45, 0x18, 0x21, 0x37, 0x64, 0x5b, 0x46, 0xe0, 0x5d, 0x30,
	0x89, 0x1c, 0xf3, 0xed, 0xfb, 0xfe, 0xb1, 0xe0, 0x04, 0xba, 0xea, 0x41, 0xd0, 0xa0, 0x8d, 0x39,
	0xef, 0x38, 0xda, 0x6b, 0xe1, 0x0d, 0x6b, 0x27, 0xd0, 0x55, 0x77, 0xb7, 0xcc, 0x99, 0xc7, 0xdf,
	0xca, 0x4e, 0xa3, 0x2f, 0x87, 0x09, 0x97, 0x37, 0xeb, 0x45, 0x48, 0xf3, 0x34, 0x4a, 0x99, 0x24,
	0xab, 0x43, 0x21, 0x09, 0xbd, 0xb5, 0x67, 0x52, 0xf0, 0xa8, 0xb8, 0x4d, 0xcc, 0x3f, 0x2d, 0xaa,
	0x26, 0x8b, 0x9e, 0x3e, 0x1d, 0xff, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x39, 0x74, 0x53, 0x6b, 0x3e,
	0x05, 0x00, 0x00,
}
